#+TITLE: 大学的第一个月
#+OPTIONS: tex: t title:nil toc:nil num:nil
* 军训

华东师大的军训向来被说很水，对我而言是个好事，因为我本身就认为军训/思政/军事理论这种东西就应该扔到垃圾堆里。

具体情况其实和上班差不多，早上七点到九点去共青场打卡，晚上六点到八点再去一次，其余时间完全自由。

不过军训还是给我留下了不太好的回忆，主要是因为教官实在过于符合一些刻板印象。

* 计科

计算机拔尖基地的课程似乎强度还没有计科大，计科学的是真正的数学分析，而我们学的是名为“数学分析”的高等数学。

程序设计第一节课也有些难评，老师自己装编译器搞了一节课也没弄好，导致近两个小时的课连 hello world 都没跑起来，姑且认为是第一节课他和我们都没进入状态（

自己日常的折腾还在继续进行，最近突发奇想在用 Common Lisp 写一个纯文本的排版工具（其实就是一个破烂DSL），目前实现了标题和段落的排版，下一步应该是加入小节，引用这些常用功能。等这个东西造完会准备把博客完全迁移到 Gopher 上。

这个月其余的时间都花在了研究 $\TeX$ 和 C 语言的各个标准上。在读完 $The \hspace{0.5em} \TeX book$ 并了解了活字排版和 Catcode/tokens 机制后，又去读了 Christan Feuersaenger 的 $Notes \hspace{0.5em} On \hspace{0.5em}  Programming \hspace{0.5em}  in \hspace{0.5em}  \TeX$，感觉现在可以真的用 $\TeX$ 来写程序了，排版效率高了很多。

C 语言其实没有特意去干什么，买了本 The C Programming Book 当睡前读物，但 ANSI C 确实有点老，Linux 现在也不支持这个规范了 (或者说就没有完全支持过，Linux 内核里一直一大堆 long long，所以要一个支持部分 C99 特性的 ANSI C 编译器才能编译)

接下来可能会把一些精力放在 METAFONT 上，在折腾文本排版的同时也想试着写个 APL 子集的解释器玩。


** OpenGenera

之前在 RCC 试图为 OpenGenera 构建一个可以直接部署的 Dockerfile，然后测试的时候发现 Arch 系在二〇〇二年就不支持 inetd 了，Genera 会没法获得时间信息，必须手动在 ZetaLisp 的 debugger 里输入再导出才能解决。

好消息是 Common Lisp 本身是支持把修改过的程序 dump 出来的，所以这个问题可以直接通过用 dump 后的二进制文件来解决。

但是 Docker 似乎没法直接使用 NFS，必须要本地机器先手动挂载再映射到 Docker 中，对于 Debian/Gentoo/Slackware 这些发行版都好说，但 Arch 裸机测试时即使已经把 NFS 的模块 modprobe 进内核还是会有问题。

所以这个项目目前先被我 private 了，准备借 Segfault 的环境构建可用环境再用 VNC 连。

** Typesetting System in Common Lisp

其实没什么好说的，使用了非常简单粗暴的方式来解决排版问题：先写一个分词器分割单词序列，给一个期望值在浮动范围内套公式计算 badness，选最小值当分行结果，但效果比预想中好很多。

$\TeX$ 的分行是一个基于坏度的动态规划算法，对于单词内部的分割它会返回比较高的坏度作为惩罚，我没有实现这个机制，因为这是纯文本的排版，用这种复杂方法并不会给出视觉上更美观的方案。

如果真有这种需要直接手调就好。毕竟排版，归根究底，is labor work.

** ELF

军训的时候想写一个 Netronics ELF-II 的模拟器，然后因为懒只写了八百多行搞了一小半就直接摆烂到现在（甚至懒到没 commit），主要是因为实现指令集太麻烦，都是重复工作 +，且 Java 勾不起我开码的兴趣+ 。

希望这个学期能在课余时间把它做完吧。

* 其它

试着翻译了 NOeSIS 小说的前两回（虽然一共有四卷），还买了漫画的初版单行本来看，不得不说一夜和千夜实在太萌了（）

下个月可能会去中古店找 NOeSIS 的同人志，看了下之前大概在税后27500円，感觉也不是不能接受，但实在太老不知道能不能买到。

评价为宅宅死前最后的幻想。

-----

然后到了大学整个人的内耗似乎比高中好一点，但和周围人的接触显著变少了很多。

日常状态：十一点半睡五点半醒（无早八七点半醒），出寝室买一个饼，吃完回寝室整理包去教室读书自习；作业和笔记用 $\TeX$ 排版，速度足够快也不怎么耗时间，周末回家打印下周交给老师；然后因为不想处理垃圾所以不点外卖，中午一碗猪排咖喱饭，晚上一碗鳕鱼咖喱饭（偶尔换成二楼的牛肉面）

只能说生活的复杂度已经被降了不少，不过衣服还是一个比较大的问题，以后可能会买五套完全一样的衣服/裤子/袜子，这样只需要两个袋子就可以了，一个放干净的衣服，一个放脏衣服，脏衣服袋子满了就扔到洗衣机里。

好处是由于袜子都一样，不用担心配对不了；穿搭方面的所有问题也能一并解决。

* 最后总结

还活着，满意了。

[[https://zeyi2.github.io][[Return to the main page]​]]
